IF (CASABLANCA_INCLUDE_DIR AND CASABLANCA_LIBRARY)
   # be silent if already found
   SET(CASABLANCA_FIND_QUIETLY TRUE)
ENDIF (CASABLANCA_INCLUDE_DIR AND CASABLANCA_LIBRARY)

FIND_PATH(CASABLANCA_INCLUDE_DIR cpprest/http_client.h PATHS "${LIB_PREFIX}/include")
FIND_LIBRARY(CASABLANCA_LIBRARY NAMES cpprest)


IF (CASABLANCA_INCLUDE_DIR AND CASABLANCA_LIBRARY)
   SET(CASABLANCA_FOUND TRUE)
ENDIF (CASABLANCA_INCLUDE_DIR AND CASABLANCA_LIBRARY)

IF (CASABLANCA_FOUND)
   IF (NOT CASABLANCA_FIND_QUIETLY)
      MESSAGE(STATUS "Found casablanca: ${CASABLANCA_LIBRARY}")
      SET(CASABLANCA_LIBS ${CASABLANCA_LIBRARY})
   ENDIF (NOT CASABLANCA_FIND_QUIETLY)
ELSE (CASABLANCA_FOUND)
   IF (CASABLANCA_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find casablanca")
   ENDIF (CASABLANCA_FIND_REQUIRED)
ENDIF (CASABLANCA_FOUND)